# Generated by Django 4.2.15 on 2024-08-16 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="App",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("version", models.CharField(blank=True, max_length=50, null=True)),
                ("apk_file", models.FileField(upload_to="apks/")),
                (
                    "first_screen_screenshot",
                    models.ImageField(blank=True, null=True, upload_to="screenshots/"),
                ),
                (
                    "second_screen_screenshot",
                    models.ImageField(blank=True, null=True, upload_to="screenshots/"),
                ),
                (
                    "video_recording",
                    models.FileField(blank=True, null=True, upload_to="recordings/"),
                ),
                (
                    "ui_hierarchy",
                    models.FileField(
                        blank=True, null=True, upload_to="ui_hierarchies/"
                    ),
                ),
                ("screen_changed", models.BooleanField(default=False)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
