# Generated by Django 4.2.15 on 2024-08-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_remove_app_uploaded_at_app_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="name",
            field=models.CharField(
                default="74ad3a090a7e4df6a3062be1c873e66a", max_length=255
            ),
        ),
    ]
